# yaml
name: APT Repo Auto Update

on:
  push:
    paths:
      - 'debs/**'
      - 'conf/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source
        uses: actions/checkout@v3

      - name: Pull repo
        run: |
           sudo git pull

      - name: Cài reprepro
        run: sudo apt-get update && sudo apt-get install -y reprepro

      - name: Xóa repo cũ (nếu có)
        run: rm -rf dists pool

      - name: Build APT repo từ debs/
        run: |
          mkdir -p dists pool
          for deb in debs/*.deb; do
            reprepro -b . includedeb stable "$deb"
          done

      - name: Commit & Push repo đã cập nhật
        run: |
          git config user.name "DangChuVM"
          git config user.email "akirahung905@gmail.com"
          git add dists pool || true
          git commit -m "Update APT repo tự động" || echo "Không có thay đổi"
          git push
      - name: Ngoài lề
        run: |
          cp /etc/apt/apt-mirrors.txt .
